#Starter pipeline
# Start with minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy and more:

trigger:
- release

pool:
  name: Hosted Ubuntu 1604

steps:
Settings
- task: UsePythonVersion@0
  displayName: 'Use Python 3.5'
  inputs:
    versionSpec: 3.5